
[+special:strings]

HTTP File System=HTTP 文件服务器
User & Login=用户与登录
Login=登录
Logout=退出登录
Change Password=更改密码
Welcome back=欢迎回来
You are already logged in, you need to log out before logging in as different user.=您已登录，若需以不同用户登录，请先退出登录。
Please login to access to your account, and check you have the correct permissions to continue=通过登录来进行身份认证，并确认您是否有权限继续操作
If you are here accidentally, you may lack the permission to access this file/folder.=如果您无意到达这里，您可能缺少访问此文件/文件夹的权限。
Tap to Back=点击返回
Input new password...=输入新密码……
Input again...=请再次输入……
Passwords not match, please re-input.=密码不匹配，请重新输入。
Password cannot be empty!=密码不能为空！
You cannot change your password!=您不能更改您的密码！
The password you entered is incorrect!=密码不正确！
The user account you entered doesn't exist!=您输入的用户不存在！
Username can't be blank!=用户名不能为空！
Password can't be blank!=密码不能为空！
Bad session, please reload!=会话无效，请刷新页面！
Homepage=主页
Search requires 1 or more characters=进行搜索需要输入 1 个或以上字符！
{.comment| Download these (number) files in a .tar archive? .}
Download these=打包这
files in a .tar archive?=个文件为 .tar 压缩文件下载吗？
Click to Archive=点击打包下载
Upload Files=上传文件
Click to sort files by this=点击以此排序文件
FileName=文件名
Date on Edit=修改日期
Size=大小
link=链接
folder=文件夹
Back to top=返回顶部
It seems nothing here...=这里好像什么都没有……
Search files here...=搜索这里的文件……
You have found a 404 page=您发现了一个 404 页面
Redirecting to the previous page...=正在重定向至上一页……
There are more people than on a worktime bus station=当前访问人数大于春运高铁站人数
Returning to previous page after traffic afford has gone lower...=交通压力缓解后将返回上一页……
There are ongoing downloads=已有正在进行的下载任务
More available after current downloads finish=当前下载结束后将可用
Please login to your account=请登录至您的管理员账户
Authorization failed=登录授权失败
Wrong username or password=用户名或密码错误
Access Denied=请求被拒绝
Nope=不行！
Upload to=上传至
Please put multiple files into a zip file=请将更多的文件压缩后上传
Back=返回
Free Space Available For Upload=服务器可供上传的剩余空间
Tap to add a selection=点这里添加一个上传项
Adding an upload selection will cause file selections reset=添加上传项将导致文件选项重置
Only the first selection supports multi-file selection=仅第一个上传项支持文件多选
Choose some files=选择一些文件
then tap the "Send file(s)" below=然后按下面的“点击上传”
New Folder=新建文件夹
Send File(s)=点击上传
Results page appears after uploads complete=上传结果将在上传完成后出现
You can also make a new folder=您也可以新建一个文件夹
Input folder name...=输入文件夹名称……
Create Folder=创建文件夹
Turns to the file list page after making a folder=新建文件夹后将返回文件列表页
Upload is not available to due to high server load=由于服务器过载，上传暂不可用
Automatically retrying after 5 seconds...=将在 5 秒后自动重试……
Upload result=上传结果
Go Back=返回文件目录
SUCCESS=成功
FAILED=失败
Uploaded=已上传
Speed=速度
Username=用户名
Password=密码
Manage=管理
Sorry, previewing this file is not sopported by your browser=抱歉，您的浏览器不支持此预览此文件
You can preview the selected file here=您可以在此处预览选择的文件
Previewing not supported, please try dowload=预览不支持，请尝试下载
Tap photo to start a slideshow; Right-click/Long-press to save=点击照片以放映图片幻灯片；右键/长按以保存
View online=在线查看
Close preview frame=关闭预览框
Expand preview frame=展开预览框
Preview Opened=预览已打开
Slide up the screen to see if using a mobile=手机用户请上滑页面查看
Tap here to download=点击此处下载
Tap here to enlarge=点击此处放大
Starting Download=开始下载
Rotate your device to fullscreen if mobile=手机用户可横屏以全屏
Enable flash plug-in in your browser/site settings to view=启用浏览器/网站设置中的 flash 插件以查看
Mobile platforms will not support flash anymore=移动端已不再支持 flash
Tap here to fullscreen=点击此处全屏
Fullscreened=已全屏
Exit by tapping the [X]=点击 [X] 退出
Exit Fullscreen=退出全屏
Playing=正在播放
Paused=已暂停
Please wait=请稍候
Getting & parsing file list...=正在获取并分析文件列表……
Move to mini player=转移至迷你播放器
Slideshow will start after 3 seconds=图片的幻灯片放映将在 3 秒后开始
Tap screen for next, rightclick/longpress to exit=点击屏幕切换下一张，右键/长按退出
Photo Thumbnails=显示照片缩略图
Play Next=播放下一个
Play Previous=播放上一个
Play mode=播放模式
Shuffled=随机
Sequenced=顺序
{.comment| eg. Do rename file.txt to favorite.txt? .}
Do=确认
Delete=删除
current FOLDER=当前【文件夹】
make a folder=创建文件夹
move=移动
rename=重命名
comment=注释
to=到
Rename as=重命名为
Input file name...=输入文件名……
Move to=移动到
Input distination...=输入地址……
Comment file=添加注释
Input something...=输入一些什么……
Move=移动
Rename=重命名
Comment=注释
Okay=确定
We met the following problems=遇到以下问题
Files were moved=文件已移动
No file was moved=没有文件被移动
Not moved=未移动
Bad session=无效的会话
Forbidden=权限不足
Illegal action=非法操作
Not authorized=身份验证失败
Failed=失败
OK=完成
Target Not found=找不到目的地
Duplicated=与现有文件（夹）重名
Input empty=输入为空
Keep me loggedin=保持登录

{.comment| Newly added strings below .}

Format=格式
Unauthorized=无身份验证
Currently you have no right to access this resource. Please login if possible.=当前您没有权力获取这里的资源。如果可能，请登录。
By checking this you also agree to use Cookies=在此打勾即表示您同意使用 Cookie
Bad session. Try to refresh the page.=会话无效。请尝试刷新页面。
Complete! Use your new password next time!=完成！后续登录请使用新密码！
Unable to view online: this site is in LAN=无法在线查看：此网站在局域网中
You can preview this document with Microsoft Office Online service=您可以使用微软在线 Office 服务查看此文档
Input old password...=输入旧密码……
Unknown error=未知错误
Old password not match=旧密码不匹配
Failed: Old password you input is wrong!=失败：输入的旧密码有误！
Macro detected=检测到宏
Macro is detected in your input. Please do not attack.=在您的输入中检测到宏。请勿攻击服务器。
