
[+special:strings]

HTTP File Server=HTTP 文件服务器
User & Login=用户与登录
Login=登录
Logout=退出登录
Change Password=更改密码
Welcome back=欢迎回来
You are already logged in, you need to log out before logging in as different user.=您已登录，若需以不同用户登录，请先退出登录。
Please login to access to your account, and check you have the correct permissions to continue=通过登录来进行身份认证，并确认您是否有权限继续操作
If you are here accidentally, you may lack the permission to access this file/folder.=如果您无意到达这里，您可能缺少访问此文件/文件夹的权限。
Tap to Back=点击返回
Input new password...=输入新密码……
Input again...=请再次输入……
Passwords not match, please re-input.=密码不匹配，请重新输入。
Password cannot be empty!=密码不能为空！
You cannot change your password!=您不能更改您的密码！
The password you entered is incorrect!=密码不正确！
The user account you entered doesn't exist!=您输入的用户不存在！
Username cannot be blank!=用户名不能为空！
Bad session, please reload!=会话无效，请刷新页面！
Homepage=主页
Search requires 1 or more characters=进行搜索需要输入 1 个或以上字符！
{.comment| Download these (number) files in a .tar archive? .}
Download these=打包这
files in a .tar archive?=个文件为 .tar 压缩文件下载吗？
Click to Archive=点击打包下载
Upload Files=上传文件
Click to sort files by this=点击以此排序文件
FileName=文件名
Size=大小
link=链接
folder=文件夹
Back to top=返回顶部
It seems nothing here...=这里好像什么都没有……
Search files here...=搜索这里的文件……
You have found a 404 page=您发现了一个 404 页面
Redirecting to the previous page...=正在重定向至上一页……
There are more people than on a worktime bus station=当前访问人数大于春运高铁站人数
Returning to previous page after traffic afford has gone lower...=交通压力缓解后将返回上一页……
There are ongoing downloads=已有正在进行的下载任务
More available after current downloads finish=当前下载结束后将可用
Please login to your account=请登录至您的管理员账户
Authorization failed=登录授权失败
Wrong username or password=用户名或密码错误
Access Denied=请求被拒绝
Nope=不行！
Upload to=上传至
Please put multiple files into a zip file=请将更多的文件压缩后上传
Back=返回
Free Space Available For Upload=服务器可供上传的剩余空间
Tap to add a selection=点这里添加一个上传项
Choose some files=选择一些文件
then tap the "Send file(s)" below=然后按下面的“点击上传”
New Folder=新建文件夹
Send File(s)=点击上传
Results page appears after uploads complete=上传结果将在上传完成后出现
You can also make a new folder=您也可以新建一个文件夹
Input folder name...=输入文件夹名称……
Create Folder=创建文件夹
Turns to the file list page after making a folder=新建文件夹后将返回文件列表页
Upload is not available to due to high server load=由于服务器过载，上传暂不可用
Automatically retrying after 5 seconds...=将在 5 秒后自动重试……
Upload result=上传结果
Go Back=返回文件目录
SUCCESS=成功
FAILED=失败
Uploaded=已上传
Speed=速度
Username=用户名
Password=密码
Manage=管理
Sorry, previewing this file is not sopported by your browser=抱歉，您的浏览器不支持此预览此文件
Previewing not supported, please try download=预览不支持，请尝试下载
Tap photo to start a slideshow; Right-click/Long-press to save=点击照片以放映图片幻灯片；右键/长按以保存
View online=在线查看
Close preview frame=关闭预览框
Expand preview frame=展开预览框
Preview Opened=预览已打开
Tap here to download=点击此处下载
Tap here to enlarge=点击此处放大
Starting Download=开始下载
Rotate your device to fullscreen if mobile=手机用户可横屏以全屏
Enable flash plug-in in your browser/site settings to view=启用浏览器/网站设置中的 flash 插件以查看
Mobile platforms will not support flash anymore=移动端已不再支持 flash
Tap here to fullscreen=点击此处全屏
Fullscreened=已全屏
Exit by tapping the [X]=点击 [X] 退出
Exit Fullscreen=退出全屏
Playing=正在播放
Paused=已暂停
Please wait=请稍候
Move to mini player=转移至迷你播放器
Slideshow will start after 3 seconds=图片的幻灯片放映将在 3 秒后开始
Tap screen for next, rightclick/longpress to exit=点击屏幕切换下一张，右键/长按退出
Photo Thumbnails=显示照片缩略图
Play Next=播放下一个
Play Previous=播放上一个
Play mode=播放模式
Shuffled=随机
Sequenced=顺序
{.comment| eg. Do rename file.txt to favorite.txt? .}
Do=确认
Delete=删除
current FOLDER=当前【文件夹】
make a folder=创建文件夹
move=移动
rename=重命名
comment=注释
to=到
Rename as=重命名为
Input file name...=输入文件名……
Move to=移动到
Input distination...=输入地址……
Comment file=添加注释
Input something...=输入一些什么……
Move=移动
Rename=重命名
Comment=注释
Okay=确定
We met the following problems=遇到以下问题
Files were moved=文件已移动
No file was moved=没有文件被移动
Not moved=未移动
Bad session=无效的会话
Forbidden=权限不足
Illegal action=非法操作
Not authorized=身份验证失败
Failed=失败
OK=完成
Target Not found=找不到目的地
Duplicated to existing file/folder=与现有文件（夹）重名
Input empty=输入为空
Keep me loggedin=保持登录
Format=格式
Unauthorized=无身份验证
Currently you have no right to access this resource. Please login if possible.=当前您没有权力获取这里的资源。如果可能，请登录。
By checking this you also agree to use Cookies=在此打勾即表示您同意使用 Cookie
Bad session. Try to refresh the page.=会话无效。请尝试刷新页面。
Complete! Use your new password next time!=完成！后续登录请使用新密码！
Unable to view online: this site is in LAN=无法在线查看：此网站在局域网中
You can preview this document with Microsoft Office Online service=您可以使用微软在线 Office 服务查看此文档
Input old password...=输入旧密码……
Unknown error=未知错误
Old password not match=旧密码不匹配
Failed: Old password you input is wrong!=失败：输入的旧密码有误！

You can tap on filename and preview here=您可以点击文件名并预览文件
{.comment| There are 0 files selected .}
There are=选择了
files selected=个文件
Enter a word or regular expression to select.=输入关键字或正则表达式以进行匹配。
Regular expression starts and ends with a slash "/".正则表达式以斜杠“/”开头和结尾。
Clear preview=清除预览
Multi select=文件多选
Cancel=取消
OKay=确定
View your file below the page!=在页面下方查看您的文件！
Last Modified=修改日期
Warning: password you entered will be sent to server with a weak encryption.=警告：您输入的密码将使用弱加密发送至服务器。
For better security please change password via HFS management window.=为保障安全请使用 HFS 用户管理窗口更改密码。
Click to sort files by extension=点击以扩展名排序文件
Your browser needs to be updated to support thumbnail lazyload.=您需要升级您的浏览器以支持照片缩略图的 Lazyload 功能。
Multi:=多文件：
Mask=蒙版/掩码选择
Invert=反选
Archive=打包
Close=关闭
Sorry, we cannot find what you prefer to see now...=抱歉，这里找不到您想要的……
A leading backslash "\\" will invert the logic.=开头添加反斜杠“\\”可以反转逻辑。
Do you want to overwrite some of your HFS settings to make this template run more efficiently?=您是否想要修改一些配置以使此模板更有效地运行？
After accepting this you may reset(clear) settings if you are going to switch to another/default template.=如果您想切换至其他/默认模板，您可以在菜单重置（清除）配置。
Browser outdated=浏览器已过期
Please update your browser to modern ones.=请升级您的浏览器。
Further info=详细信息
You are using an unsupported browser, which will result in an unjoyful experience.=您在使用不受支持的浏览器，这会影响您的浏览体验。
If you are using a dual-core browser, please switch core at right side of address bar.=如果您在使用双核浏览器，请在地址栏右侧切换内核。
Or you may update your browser to new ones, such as: Chrome, Chromium, Edge, Firefox, Opera, Safari etc.=或者您可以升级到新的浏览器，比如：Chrome, Chromium, Edge, Firefox, Opera, Safari 等等。
Main Page=主页
Already Downloading=已有下载任务
Overload=服务器过载
Search=搜索
Search whatever you want...=搜索您想要的……
Select default search engine:=选择默认搜索引擎：
My Personal Site=我的个人主页
My Projects=我的作品
Making stuffs makes me happy!=创作，乐在其中！
My Pictures=我的照片
Snap of my memorable times!=记录美好瞬间！
My Videos=我的视频
Go across past experiences!=穿越时空，回首往事！
Music collection=音乐集锦
A special form of art!=一种不同寻常的艺术！
Server root directory=服务器根目录
View the server's structure=查看服务器结构
Administration Login=管理员登录
Get more permissions by logging-in.=登录以获取更多权限。
Ecosia=Ecosia
Swisscows=Swisscows
Oscobo=Oscobo
Qwant=Qwant
Bing=必应
Google=谷歌
Baidu=百度
Sogou=搜狗
360 So=360 好搜
Wolfram=Wolfram
Converting=正在转换
to .html format.=到 .html 格式。
Conversion Started=转换开始
Conversion complete.=转换完成。
After refreshing the page, find the .html file.=刷新页面后，请寻找相应的 .html 文件并打开。
Conversion failed.=转换失败。
Server has no LibreOffice installed.=服务器端未安装 LibreOffice。
You may convert this document to HTML format and view that directly.=您可以将此文档转换为 HTML 格式并直接预览。
Convert to HTML=转换为 HTML
No LibreOffice installed=未安装 LibreOffice
